[project]
name = "math-tagger-mlops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ilya E", email = "elushoviv@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
math-tagger-mlops = "math_tagger_mlops:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
