# Defaults
defaults:
  - _self_
  - data: math_dataset
  - model: logreg
  - train: default

# Global settings
project_name: "math-tagger-mlops"
seed: 99
mode: "train" # for command menu
input_text: ""

# MLflow settings
mlflow:
  experiment_name: ${project_name}
  tracking_uri: "http://127.0.0.1:8080"
